fileName1 = input("Enter file to be read from: ")
fileName2 = input("Enter file to be appended to: ")
fin = open(fileName1, "r")
data2 = fin.read()
fin.close()
fout = open(name2, "a")
fout.write(data2)
fout.close()
